### ISSUE TITLE
grid_sampler

### ISSUE THREAD

**Issue by wuxiaolianggit** [talebolano/Tensorrt-Deformable-Detr#2]
Hello, may I ask how to register the function 'grid_sampler'? @talebolano

**Comment by talebolano** [comment]
> Hello, may I ask how to register the function 'grid_sampler'? @talebolano

In tensorrt？you can see [gridSamplePlugin](https://github.com/grimoire/amirstan_plugin/tree/master/src/plugin/gridSamplePlugin) and find answer

**Comment by wuxiaolianggit** [comment]
Hello, what I mean is, do you need to register the grid_sampler in Torch for your code? Or can you directly run it after installing the environment in requirements.txt? I don't need to do any registration work for grid_sampler.@ @talebolano

**Comment by wuxiaolianggit** [comment]
I only need to convert PTH to ONNX, I don't need to convert it into a TensorRT model.

**Comment by talebolano** [comment]
> 
you can register the grid_sampler in onnx like this
```bash
python3 onnx_deformable_detr.py --config ${mmdet_path}/configs/deformable_detr/deformable_detr_twostage_refine_r50_16x2_50e_coco.py --checkpoint ${mmdet_path}/work_dirs/deformable_detr_twostage_refine_r50_16x2_50e_coco_20210419_220613-9d28ab72.pth --output deformable_detr.onnx --h 750 --w 1333 --usegridsample
```
